import { createContext, useContext } from "react";
//import json file
import menu1 from "$lib/menu.json";

const MenuContext = createContext();

export function AppMenuProvider({ children })
{
    
    const menu = {
        "starters": [
            {
                name: "Chicken",
                veg: false,
                Qtype: "pcs",
                description: "Chicken is a meat dish made of meat and skin with a corpulent or meaty exterior. It is a source of energy and is the most frequently consumed meat.",
                cuisine: "Indian",
            },
            {
                name: "Mutton",
                veg: false,
                Qtype: "pcs",
                description: "Mutton is a meat dish made of the young body of a sheep",
                cuisine: "Indian"
            },
            {
                name: "Fish",
                veg: false,
                Qtype: "pcs",
                description: "Fish is a food that is a part of the animal kingdom and is a member of the class of animals called fish.",
                cuisine: "Indian"
            },
            {
                name: "Egg",
                veg: false,
                Qtype: "pcs",
                description: "Egg is a soft, light-bodied egg, which is the yolk of a hard-shelled egg.",
                cuisine: "Chinese"
            },
            {
                name: "Vegetables",
                veg: true,
                Qtype: "kg",
                description: "Vegetables are plants that are consumed as food.",
                cuisine: "French"
            },
            {
                name: "Fruits",
                veg: true,
                Qtype: "pcs",
                description: "Fruits are fruits that are consumed as food.",
                cuisine: "French"
            },
            {
                name: "Milk",
                veg: true,
                Qtype: "kg",
                description: "Milk is a dairy product that is a food that is produced by mammals.",
                cuisine: "Japanese"
            }
        ],
        mains: [
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Chicken Curry",
                veg: false,
                Qtype: "kg",
                description: "Chicken Curry is a dish made from chicken and vegetables.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Mutton Curry",
                veg: false,
                Qtype: "kg",
                description: "Mutton Curry is a dish made from mutton and vegetables.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Fish Curry",
                veg: false,
                Qtype: "kg",
                description: "Fish Curry is a dish made from fish and vegetables.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Egg Curry",
                veg: false,
                Qtype: "kg",
                description: "Egg Curry is a dish made from egg and vegetables.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Tandoori Chicken",
                veg: false,
                Qtype: "pcs",
                description: "Tandoori Chicken is a dish made from chicken.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Tandoori Mutton",
                veg: false,
                Qtype: "pcs",
                description: "Tandoori Mutton is a dish made from mutton.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Lady Finger",
                veg: true,
                Qtype: "kg",
                description: "Lady Finger is a dish made from lady finger.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Chilli Paneer",
                veg: true,
                Qtype: "kg",
                description: "Chilli Paneer is a dish made from chilli paneer.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: false,
                name: "Paneer Tikka",
                veg: true,
                Qtype: "kg",
                description: "Paneer Tikka is a dish made from paneer.",
                cuisine: "Indian"
            },
            {
                isRice: true,
                isPoori: false,
                isBread: false,
                name: "Rice",
                veg: true,
                Qtype: "kg",
                description: "Rice is a food that is a part of the plant kingdom and is a member of the class of plants called graminoids.",
                cuisine: "Indian"
            },
            {
                isRice: true,
                isPoori: false,
                isBread: false,
                name: "Rice2",
                veg: true,
                Qtype: "kg",
                description: "Rice is a food that is a part of the plant kingdom and is a member of the class of plants called graminoids.",
                cuisine: "Indian"
            },
            {
                isRice: true,
                isPoori: false,
                isBread: false,
                name: "Rice3",
                veg: true,
                Qtype: "kg",
                description: "Rice is a food that is a part of the plant kingdom and is a member of the class of plants called graminoids.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: true,
                isBread: true,
                name: "Poori",
                veg: true,
                Qtype: "pcs",
                description: "Poori is a dish made from rice and vegetables.",
                cuisine: "Indian"
            },
            {
                isRice: false,
                isPoori: false,
                isBread: true,
                name: "Naan",
                veg: true,
                Qtype: "pcs",
                description: "Naan is a flatbread made from bread.",
                cuisine: "Indian"
            }
        ],
        desserts: [
            {
                name: "Ice Cream",
                veg: true,
                Qtype: "kg",
                description: "Ice Cream is a dessert that is made from milk.",
                cuisine: "Indian"
            },
            {
                name: "Gulab Jamun",
                veg: true,
                Qtype: "pcs",
                description: "Gulab Jamun is a dessert that is made from milk.",
                cuisine: "Indian"
            },
            {
                name: "Gajar Ka Halwa",
                veg: true,
                Qtype: "kg",
                description: "Gajar Ka Halwa is a dessert that is made from milk.",
                cuisine: "Indian"
            }
        ]
    };

    const allMenus=[
        {
         "id": 600,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Tandoori Paneer Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Tandoori_Paneer_Tikka_g6VzMK35Y.jfif?updatedAt=1678369542454"
        },
        {
         "id": 601,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Reshmi Mushroom",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 180,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Reshmi_Mushroom_hpSslVjbC1.png?updatedAt=1678714359736"
        },
        {
         "id": 602,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Honey chilli Baby Potato",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 260,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Honey_Chilli_Potato_Ho3aaPBPj1.webp?updatedAt=1678714348038"
        },
        {
         "id": 603,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Churasco Pineapple",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 420,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.31.54_PM_CPjbJTp_HV.jpeg?updatedAt=1678865585347"
        },
        {
         "id": 604,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Tandoori Malai Chap",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 380,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.31.55_PM_Gje8ZHo-d9.jpeg?updatedAt=1678865585081"
        },
        {
         "id": 605,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Veg Kebab",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 180,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.24.31_PM__1__OS3SlxIX48.jpeg?updatedAt=1678865585152"
        },
        {
         "id": 606,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Cajun spice Potato",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 220,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.24.40_PM_EE4mq0NRkD.jpeg?updatedAt=1678865585367"
        },
        {
         "id": 607,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Crispy Corn",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Crispy_Corn_E6WZuoUXD.jpg?updatedAt=1678369540596"
        },
        {
         "id": 608,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Malai Broccoli",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Malai_Broccoli_EtwPcclDFg.jpg?updatedAt=1678714350117"
        },
        {
         "id": 609,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Cheesy Triangles (Samosa patti)",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 288,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.31.55_PM__1__jqsycMjW5.jpeg?updatedAt=1678865584715"
        },
        {
         "id": 610,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Veggie Fingers",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 216,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Veggie_Fingers_Fx1Yrwnb7q.webp?updatedAt=1678714366781"
        },
        {
         "id": 611,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Veg Sheek Kebab ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Veg_Sheek_Kebab_jWqnelwfA.jfif?updatedAt=1678369543804"
        },
        {
         "id": 612,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Hara bhara Kebab ",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 180,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Hara_bhara_Kebab_e894C6Lspc.jpg?updatedAt=1678369540056"
        },
        {
         "id": 613,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Dahi ke kebab",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 180,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Dahi_k_kebab_i3I25E8Eud.jpg?updatedAt=1678714344655"
        },
        {
         "id": 614,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Veg Manchurian Dry",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 300,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Veg_Manchurian_Dry_wpmKKNwLx.jpg?updatedAt=1678714365357"
        },
        {
         "id": 615,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Gobi Manchurian Dry",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 300
        },
        {
         "id": 616,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Manchurian Dry- Mushroom",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 660,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Manchurian_-_Mushroom_RJGMvTLyo.png?updatedAt=1678714350993"
        },
        {
         "id": 617,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Achari Paneer Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Achari_Paneer_Tikka_wxG-Kx-QH.jpg?updatedAt=1678714329845"
        },
        {
         "id": 618,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Pudina Paneer Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Pudina_Paneer_Tikka_VnX-J6Oj1.webp?updatedAt=1678369542361"
        },
        {
         "id": 619,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Malai Paneer Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Malai_Paneer_Tikka_Xz762ReXH.jpg?updatedAt=1678714350047"
        },
        {
         "id": 620,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Tandoori Achari Chaap",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 380,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Tandoori_Achari_Chaap_D4Z0T6qFMq.jpg?updatedAt=1678714362292"
        },
        {
         "id": 621,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Tandoori Achari Aloo",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 300,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Tandoori_Achari_Aloo_FzJr2OdBmC.jpg?updatedAt=1678714362249"
        },
        {
         "id": 622,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Schzwan Paneer Chilly Dry",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 600,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Schzwan_Paneer_Chilly_Dry_rvUYUcm-Xj.jpg?updatedAt=1678714360197"
        },
        {
         "id": 623,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Paneer Chilly Dry- Classic",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 600,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Paneer_Chilly_-_Classic_6nAUeLAKu.jpg?updatedAt=1678714355781"
        },
        // {
        //  "id": 624,
        //  "city": "bangalore",
        //  "menu_label": "Starters ",
        //  "name": "Pepper Paneer Chilly Fry",
        //  "Qtype": "kg",
        //  "cuisine": "Pan Asian",
        //  "veg": true,
        //  "mealType": "Starter",
        //  "meal": "Express",
        //  "selling_price": 600,
        //  "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Pepper_Paneer_Chilly_Fry_Iv-V3CfW1O.jpg?updatedAt=1678714357391"
        // },
        {
         "id": 625,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "French Fries ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 560,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/French_Fries_-Z81oi9d9.jpg?updatedAt=1678714346020"
        },
        {
         "id": 626,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Kalmi Chicken  Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Kalmi_Chicken__Tikka_KMCijH7ve0.jpg?updatedAt=1678714349033"
        },
        {
         "id": 627,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "BBQ Chicken Wings",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.24.41_PM_6u1LedpLN-.jpeg?updatedAt=1678865585069"
        },
        {
         "id": 628,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Coastal BBQ Fish Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 264,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Coastal_BBQ_Fish_Tikka_czeVj-C6w4.jpg?updatedAt=1678714343686"
        },
        {
         "id": 629,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Tandoori Fish Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 264,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Tandoori_Fish_Tikka_8UE6M0Z0E.jpg?updatedAt=1678714362413"
        },
        {
         "id": 630,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Chilli Garlic Prawns",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 312,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Chilli_Garlic_Chicken_HonGcYRexF.jpg?updatedAt=1678714339161"
        },
        {
         "id": 631,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Punjabi Tangdi",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 984,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Punjabi_Tangdi_gZ5XsEP_s.jpg?updatedAt=1678714359531"
        },
        {
         "id": 632,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "chicken seekh kebab  (5.5\")",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 860,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.24.31_PM__2__7TPsyziSd8.jpeg?updatedAt=1678865585356"
        },
        {
         "id": 633,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Pudina Chicken Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Pudina_Chicken_Tikka_5YTd51zTEF.jpg?updatedAt=1678714358275"
        },
        {
         "id": 634,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Achari Chicken Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Express",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Achari_Chicken_Tikka_IwLHYO8sRT.jpg?updatedAt=1678714330142"
        },
        {
         "id": 635,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Amritsari Fish Tikka",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Regular",
         "selling_price": 312,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Amritsari_Fish_Tikka_uAphGfRl2Y.jpeg?updatedAt=1678714330267"
        },
        {
         "id": 636,
         "city": "bangalore",
         "menu_label": "Starters ",
         "name": "Mutton Sheekh Kebab",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Starter",
         "meal": "Regular",
         "selling_price": 1540,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/starters\/Mutton_Sheekh_Kebab_y-Tdt5d80.jpeg?updatedAt=1678714354839"
        },
        {
         "id": 637,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Tawa Veg",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 420,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/Tawa-Sabzi-fry-recipe-02_xuFnH7IRP.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678443955717"
        },
        {
         "id": 638,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Kadai Veg",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 420,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/kadai-vegetables-recipe-2_bdXNXFPdw.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678443586835"
        },
        {
         "id": 639,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Aloo Gobi Tamatar",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/Aloo_Gobi_Tamatar_g7wDjigEJP.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678442799279"
        },
        {
         "id": 640,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Jeera Aloo",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/Jeera_aloo_EXJONKgusC.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677570210193"
        },
        {
         "id": 641,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Rajma Masala",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/Rajma_Masala_un10mzr3uv.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677570212216"
        },
        {
         "id": 642,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Chole Masala",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/Chole_Masala_6YpyUcvHOJ.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677570209836"
        },
        {
         "id": 643,
         "city": "bangalore",
         "menu_label": "Mains-Dry",
         "name": "Egg Masala",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 540,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dry\/Egg-Curry-Thumbnail_0EbciiaEk.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678443351596"
        },
        {
         "id": 644,
         "city": "bangalore",
         "menu_label": "Mains-Dal",
         "name": "Dal Makhani",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 460,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dal\/Dal_Makhanni_NvtdLBIrgu.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677568906121"
        },
        {
         "id": 645,
         "city": "bangalore",
         "menu_label": "Mains-Dal",
         "name": "Yellow Dal Fry",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dal\/Dal_Fry_Nhqor_M9xY.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677568906089"
        },
        {
         "id": 646,
         "city": "bangalore",
         "menu_label": "Mains-Dal",
         "name": "Dal Tadka",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 360,
         "QTY": 1.5,
         "Total": 540,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Dal\/Tadkewali_dal_An1Gbq2Bt.JPG?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677568908371"
        },
        {
         "id": 647,
         "city": "bangalore",
         "menu_label": "Mains-Paneer",
         "name": "Paneer Butter masala",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 720,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Paneer_butter_masala_tisY5YsRoa.jpg?updatedAt=1678696394805"
        },
        {
         "id": 648,
         "city": "bangalore",
         "menu_label": "Mains-Paneer",
         "name": "Paneer Kadai",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 720,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Kadai_Paneer_blffCYrnu.jpg?updatedAt=1678696021394"
        },
        {
         "id": 649,
         "city": "bangalore",
         "menu_label": "Mains-Paneer",
         "name": "Paneer Lababdar ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 720,
         "QTY": 2,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Paneer_Lababdar_H3Iu8-gq4.jpg?updatedAt=1678696309456"
        },
        {
         "id": 650,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Sabz E Bahar ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 420,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/sabz_e_bahar_XVOv_-G5_.jfif?updatedAt=1678697878487"
        },
        {
         "id": 651,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Veg Manchurian Gravy",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/veg-manchurian_pDXj6sUVX.jpg?updatedAt=1678699230179"
        },
        {
         "id": 652,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chilli Chicken with Bone ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 800,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/easy-chinese-chilli-chicken-dry-4_TaK_-v2Mfz.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678445859897"
        },
        {
         "id": 653,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Veg Kofta Curry ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 500,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Veg_Kofta_Curry_5MeT1zfQqq.jpg?updatedAt=1678369580842"
        },
        {
         "id": 654,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Malai Kofta Gravy ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 560,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Malai_Kofta_Curry_-17lM_82dd.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678369576081"
        },
        {
         "id": 655,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Paneer Kofta Gravy",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 560,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Paneer_Kofta_curry_RHqI-e8u9.jpg?updatedAt=1678696168742"
        },
        {
         "id": 656,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Butter chicken masala",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 900,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Butter_chicken_recipe_U0qYKv4Bm_.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678445208251"
        },
        {
         "id": 657,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Fish curry",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 840,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/fish_curry_ACm5OmxEAU.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678446351350"
        },
        {
         "id": 658,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Mutton Rogan Josh",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 1200,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Mutton_Roganjosh_YPBeslDvfY.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678369578226"
        },
        {
         "id": 659,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chicken Kadai",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 800,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Chicken_Kadahi_MXN4Hkplzm.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678369573190"
        },
        {
         "id": 660,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chicken Lababdar",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 800,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Chicken_Lababdar_J2IAgWWHA.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678369575089"
        },
        {
         "id": 661,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Punjabi Chicken Curry",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 800,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/punjabi_chicken_curry__NKf6IEA2.jpg?updatedAt=1678697405297"
        },
        {
         "id": 662,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Malabar\/Kerala Fish Curry ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 1000,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/malbarkerlafish_evqQvkaZt.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678447995481"
        },
        {
         "id": 663,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Mutton Gravy(with bone) - Kosha",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 1500,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/84667091_jye7dVCZO.webp?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678448361330"
        },
        {
         "id": 664,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Veg Manchurian Gravy",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/veg-manchurian_pDXj6sUVX.jpg?updatedAt=1678699230179"
        },
        {
         "id": 665,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Veg Manchurian Gravy - Hunan Sauce",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Veg_Manchurian_in_hunan_sauce_tIpvxXeMp.jpg?updatedAt=1678699162004"
        },
        {
         "id": 666,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Veg Manchurian Gravy - Chilli Garlic Sauce",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 400,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Veg_manchurian_Gravy_-jQJ7DdOsH.jpg?updatedAt=1678369581549"
        },
        {
         "id": 667,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Paneer Manchurian Gravy",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 660,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/paneer_manchurian_garvy_DaJQGkNfR.jpg?updatedAt=1678696519564"
        },
        {
         "id": 668,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chicken Manchurian - Chilli Garlic sauce",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 840,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Chilli_Garlic_Chicken_in_Shchezwan__Sauce_uDz3ftqQw.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678369575365"
        },
        {
         "id": 669,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chicken Manchurian - Schzewan Sauce",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 840,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/53241077_8U7IIAxRE.jfif?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678445700485"
        },
        {
         "id": 670,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chinese Gravy - ( Fish ) in choice of sauce (Chilli Garlic, Schzwan)",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 1000,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/1735795_6s6fvtXo9.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678446127951"
        },
        {
         "id": 671,
         "city": "bangalore",
         "menu_label": "Mains-Gravy",
         "name": "Chinese Gravy - ( Prawns ) in choice of sauce (Chilli Garlic, Schzwan)",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 1500,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Mains-Gravy\/Asian-Chilli-Garlic-Prawns-1_5_2Fp72RoU_C.webp?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678446191152"
        },
        {
         "id": 672,
         "city": "bangalore",
         "menu_label": "Pasta",
         "name": "Arabiata Pasta (Tomota Sauce)",
         "Qtype": "kg",
         "cuisine": "Continental",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 500,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-pasta\/Pasta_Arabiatta_M5PLVkz3m.jpg?updatedAt=1678703443217"
        },
        {
         "id": 673,
         "city": "bangalore",
         "menu_label": "Pasta",
         "name": "Alfredo Pasta (White Sauce)",
         "Qtype": "kg",
         "cuisine": "Continental",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 440,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-pasta\/Pasta_Alfredo_WhWWyh1qog.jfif?updatedAt=1678703443350"
        },
        {
         "id": 674,
         "city": "bangalore",
         "menu_label": "Pasta",
         "name": "Veg Mac N Cheese Pasta",
         "Qtype": "kg",
         "cuisine": "Continental",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 500,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-pasta\/Mac_N_cheese_XgsZIkAvA.jpg?updatedAt=1678703442753"
        },
        {
         "id": 675,
         "city": "bangalore",
         "menu_label": "Pasta",
         "name": "Chicken Mac-n-Cheese Pasta",
         "Qtype": "kg",
         "cuisine": "Continental",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 660,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-pasta\/chicken_mac_n_cheese_Ao1R4Ft4X.jpg?updatedAt=1678703894394"
        },
        {
         "id": 676,
         "city": "bangalore",
         "menu_label": "Pasta",
         "name": "Chicken Arabiata Pasta (Tomota Sauce)",
         "Qtype": "kg",
         "cuisine": "Continental",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 660,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-pasta\/Pasta_Arabiatta_-_Chicken_0axkXcDMb.jpg?updatedAt=1678703443333"
        },
        {
         "id": 677,
         "city": "bangalore",
         "menu_label": "Pasta",
         "name": "Chicken Alfredo Pasta (White Sauce)",
         "Qtype": "kg",
         "cuisine": "Continental",
         "veg": false,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 660,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-pasta\/Pasta_Alfredo-_Chicken_SLM3fhIXSt.jpg?updatedAt=1678703442813"
        },
        {
         "id": 678,
         "city": "bangalore",
         "menu_label": "Heavy Snack",
         "name": "Chicken Keema Without PAV",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 1000,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Heavy_Snack\/shutterstock_1528128245-750x500_KdMqUBu8X.webp?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678444408119"
        },
        {
         "id": 679,
         "city": "bangalore",
         "menu_label": "Heavy Snack",
         "name": "Pav Bhaji (1 Kg includes 20 Pav)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 900,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Heavy_Snack\/Pav_Bhaji_8EfQkeGkCj.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677568190493"
        },
        {
         "id": 680,
         "city": "bangalore",
         "menu_label": "Heavy Snack",
         "name": "Extra Pav",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Regular",
         "selling_price": 240,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Heavy_Snack\/Mumbai-Ladi-Pav-Eggless-Dinner-Rolls-2_4QhUuWiQyc.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678361925837"
        },
        {
         "id": 681,
         "city": "bangalore",
         "menu_label": "Salad",
         "name": "Mix Veg Salad ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 120,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/healthy-vegetable-salad-recipe-1_UkqoBllSI.jpg?updatedAt=1678709368110"
        },
        {
         "id": 682,
         "city": "bangalore",
         "menu_label": "Sides",
         "name": "Raita",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 220,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/sides\/Boondi-Raita_WRbj83r5z.webp?updatedAt=1678709506052"
        },
        {
         "id": 683,
         "city": "bangalore",
         "menu_label": "Sides",
         "name": "Plain Curd",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 180,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/sides\/plain_curd_wXKUZIaUy.webp?updatedAt=1678709505658"
        },
        {
         "id": 684,
         "city": "bangalore",
         "menu_label": "Sides",
         "name": "Salan",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Main course",
         "meal": "Express",
         "selling_price": 300,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/sides\/Salan_SaUR-lUqV.jpg?updatedAt=1678709505887"
        },
        {
         "id": 685,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Chicken Dum Biryani (Includes Raita)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 585,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Murg_Dum_Biryani_uFo9s5F1rt.jpg?updatedAt=1678707742839"
        },
        {
         "id": 686,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Mutton Dum Biryani (Includes Raita)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 765,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Mutton_Dum_Biryani_ZTZNx_SIg4.jpg?updatedAt=1678707742663"
        },
        {
         "id": 687,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Veg Dum Biryani (Includes Raita)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 385,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Veg_Biryani_HVy8ilB2c5.jfif?updatedAt=1678707745843"
        },
        {
         "id": 688,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Paneer Tikka Dum Biryani (Includes Raita)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 465,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Paneer_Tikka_Dum_Biryani__Serves_1__of0h4iI-fM.webp?updatedAt=1678707743078"
        },
        {
         "id": 689,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Prawns Biryani (Includes Raita)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 1150,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Prawns_Biryani_aD_Hbek_Z.jpg?updatedAt=1678707745436"
        },
        {
         "id": 690,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Chicken Seekh Dum Biryani (Includes Raita)",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 665,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Chicken_Seekh_Dum_Biryani__Serves_1__1MXHWxxi_.webp?updatedAt=1678707739671"
        },
        {
         "id": 691,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Curd Rice",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 220,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Curd_Rice_9Bd_1eZsp.webp?updatedAt=1678707742727"
        },
        {
         "id": 692,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Steamed Rice ",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 340,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/steamed_rice_m0sOWyi6fo.jpg?updatedAt=1678707745875"
        },
        {
         "id": 693,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Flavoured Rice \/ Veg Pulao",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 340,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Veg_Pulao_Tt5foOOj9t.jpg?updatedAt=1678707745934"
        },
        {
         "id": 694,
         "city": "bangalore",
         "menu_label": "Breads",
         "name": "Butter Naan",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 384,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Breads_section\/Butter_Naan_AbyBmnuEM.jfif?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677566600911"
        },
        {
         "id": 695,
         "city": "bangalore",
         "menu_label": "Breads",
         "name": "Lachha Paratha",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 480,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.24.29_PM_nXUoxikoi.jpeg?updatedAt=1678866336704"
        },
        {
         "id": 696,
         "city": "bangalore",
         "menu_label": "Breads",
         "name": "Plain Naan",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/plain_naan_H4tMKXwQf.png?updatedAt=1678866340625"
        },
        {
         "id": 697,
         "city": "bangalore",
         "menu_label": "Breads",
         "name": "Poori - 4\"",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Regular",
         "selling_price": 120,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Breads_section\/Pooris_Bwwohvi8xV.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677566601031"
        },
        {
         "id": 698,
         "city": "bangalore",
         "menu_label": "Breads",
         "name": "Wheat Paratha",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Regular",
         "selling_price": 480,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-15_at_1.18_1_6ETBJum1i.png?updatedAt=1678867144793"
        },
        {
         "id": 699,
         "city": "bangalore",
         "menu_label": "Breads",
         "name": "Butter Kulcha",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Regular",
         "selling_price": 480,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Breads_section\/-butter-kulcha_TU6Fh_eIS.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678360434053"
        },
        {
         "id": 700,
         "city": "bangalore",
         "menu_label": "Noodle",
         "name": "Veg Hakka Noodle ",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-_Noodles\/Veg-Hakka-Noodles_QR-5E9S6f.jpg?updatedAt=1678700561020"
        },
        {
         "id": 701,
         "city": "bangalore",
         "menu_label": "Noodle",
         "name": "Veg Chilli Garlic Noodle",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-_Noodles\/Veg_Chilli_Garlic_Noodle_4RD7efw8g.jpg?updatedAt=1678700561127"
        },
        {
         "id": 702,
         "city": "bangalore",
         "menu_label": "Noodle",
         "name": "Veg Schezwan Noodle",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-_Noodles\/Veg_Schezwan_Noodle_LAUEgGhAst.webp?updatedAt=1678700561467"
        },
        {
         "id": 703,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Veg Fried Rice",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Veg_Fried_Rice_Due7MX_Lw.jpg?updatedAt=1678707745865"
        },
        {
         "id": 704,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Veg Schezwan Rice",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": true,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Schezwan_Fried_Rice_37tuXAX35.jpg?updatedAt=1678707745471"
        },
        {
         "id": 705,
         "city": "bangalore",
         "menu_label": "Noodle",
         "name": "Chicken Hakka Noodle",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 620,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-_Noodles\/Chicken_Hakka_Noodle_u-NUNWppgj.jpg?updatedAt=1678700558040"
        },
        {
         "id": 706,
         "city": "bangalore",
         "menu_label": "Noodle",
         "name": "Chicken Chilli Noodle",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 620,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-_Noodles\/Chicken_Chilli_Noodle_ASfJF9C85.webp?updatedAt=1678700557916"
        },
        {
         "id": 707,
         "city": "bangalore",
         "menu_label": "Noodle",
         "name": "Chicken Schezwan Noodle",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 620,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains-_Noodles\/Chicken_Schezwan_Noodle_bD1TTFMkmW.jpg?updatedAt=1678700557767"
        },
        {
         "id": 708,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Chicken Fried Rice",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 620,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Chicken_Fried_Rice_stvauM5Rwt.png?updatedAt=1678707739145"
        },
        {
         "id": 709,
         "city": "bangalore",
         "menu_label": "Rice",
         "name": "Chicken Schezwan Rice",
         "Qtype": "kg",
         "cuisine": "Pan Asian",
         "veg": false,
         "mealType": "Bread+Rice",
         "meal": "Express",
         "selling_price": 620,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/mains_-_rice\/Chicken_Schezwan_Rice_cqnvAX_v4z.jpg?updatedAt=1678707739662"
        },
        {
         "id": 710,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Chocolate Brownie",
         "Qtype": "pcs",
         "cuisine": "Continental",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/Chocolate_Brownie_gdNG9TVpvF.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677567299211"
        },
        {
         "id": 711,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Chocolate Pastry",
         "Qtype": "pcs",
         "cuisine": "Continental",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 360,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/new_bbq_pics\/WhatsApp_Image_2023-03-14_at_1.24.31_PM_9WO12xtZBS.jpeg?updatedAt=1678865585349"
        },
        {
         "id": 712,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Pineapple Pastry",
         "Qtype": "pcs",
         "cuisine": "Continental",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 130,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/pineapple_pastry_jVsaonvIm.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678360916760"
        },
        {
         "id": 713,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Fruit custard",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 440,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/Fruit-Custard-500x500_FLvNrsaob1.webp?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678444686445"
        },
        {
         "id": 714,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Moong Dal Halwa",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 520,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/Moong_Dal_Halwa_xL4oJDR-p.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677567299119"
        },
        {
         "id": 715,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Angoori Gulab Jamun",
         "Qtype": "pcs",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 96,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/Angoori_Gulab_Jamun_DYblq2N25N.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1677567299198"
        },
        {
         "id": 716,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Paysam",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 260,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/Semiyan-Payasam-590x436_4zE2yQ1PK.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678444741108"
        },
        {
         "id": 717,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Kesariya Phirni",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 280,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/Kesar-Phirni_xaNxEPlh8E.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678444806012"
        },
        {
         "id": 718,
         "city": "bangalore",
         "menu_label": "Dessert",
         "name": "Shahi meetha",
         "Qtype": "kg",
         "cuisine": "Indian",
         "veg": true,
         "mealType": "Dessert",
         "meal": "Express",
         "selling_price": 500,
         "Images": "https:\/\/ik.imagekit.io\/ws3brr13khq\/Dessert_Section\/download_yhhu3aZ-Y.jfif?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1678444865417"
        }
       ]
    var cuisines = [
        "All",
        "Pan Asian",
        "Indian"
        // "Bengali",
        // "Chinese",
        // "French",
        // "Japanese"
    ]
    var cities = [
        "Mumbai",
        "Thane",
        "Navi-Mumbai",
        "Bangalore",
        "Delhi",
        "Gurgaon",
        "Noida",
        "Ghaziabad",
        


    ]
    var occasions = [
        
        "Birthday",
        "House Party",
        "Pooja @ Home",
        "Pre-Wedding",
        "Office Party",
        "House Warming",
        "Kitty Party",
        "Kids Party",
        "Baby Shower",
        "Anniversary",
        "Inviting Guests",
        "Festivals",
        "Others",
       
    ]

    return (
        <MenuContext.Provider value={{ menu, cuisines,allMenus, cities, occasions }}>
            {children}
        </MenuContext.Provider>
    )
}

export function useAppMenu()
{
    return useContext(MenuContext);
}