import { createContext, useContext } from "react";
//import json file
import menu1 from "$lib/menu.json";

const MenuContext = createContext();

export function AppMenuProvider({ children }) {
  const menu = {
    starters: [
      {
        name: "Chicken",
        veg: false,
        Qtype: "pcs",
        description:
          "Chicken is a meat dish made of meat and skin with a corpulent or meaty exterior. It is a source of energy and is the most frequently consumed meat.",
        cuisine: "Indian",
      },
      {
        name: "Mutton",
        veg: false,
        Qtype: "pcs",
        description: "Mutton is a meat dish made of the young body of a sheep",
        cuisine: "Indian",
      },
      {
        name: "Fish",
        veg: false,
        Qtype: "pcs",
        description:
          "Fish is a food that is a part of the animal kingdom and is a member of the class of animals called fish.",
        cuisine: "Indian",
      },
      {
        name: "Egg",
        veg: false,
        Qtype: "pcs",
        description:
          "Egg is a soft, light-bodied egg, which is the yolk of a hard-shelled egg.",
        cuisine: "Chinese",
      },
      {
        name: "Vegetables",
        veg: true,
        Qtype: "kg",
        description: "Vegetables are plants that are consumed as food.",
        cuisine: "French",
      },
      {
        name: "Fruits",
        veg: true,
        Qtype: "pcs",
        description: "Fruits are fruits that are consumed as food.",
        cuisine: "French",
      },
      {
        name: "Milk",
        veg: true,
        Qtype: "kg",
        description:
          "Milk is a dairy product that is a food that is produced by mammals.",
        cuisine: "Japanese",
      },
    ],
    mains: [
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Chicken Curry",
        veg: false,
        Qtype: "kg",
        description:
          "Chicken Curry is a dish made from chicken and vegetables.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Mutton Curry",
        veg: false,
        Qtype: "kg",
        description: "Mutton Curry is a dish made from mutton and vegetables.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Fish Curry",
        veg: false,
        Qtype: "kg",
        description: "Fish Curry is a dish made from fish and vegetables.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Egg Curry",
        veg: false,
        Qtype: "kg",
        description: "Egg Curry is a dish made from egg and vegetables.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Tandoori Chicken",
        veg: false,
        Qtype: "pcs",
        description: "Tandoori Chicken is a dish made from chicken.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Tandoori Mutton",
        veg: false,
        Qtype: "pcs",
        description: "Tandoori Mutton is a dish made from mutton.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Lady Finger",
        veg: true,
        Qtype: "kg",
        description: "Lady Finger is a dish made from lady finger.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Chilli Paneer",
        veg: true,
        Qtype: "kg",
        description: "Chilli Paneer is a dish made from chilli paneer.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: false,
        name: "Paneer Tikka",
        veg: true,
        Qtype: "kg",
        description: "Paneer Tikka is a dish made from paneer.",
        cuisine: "Indian",
      },
      {
        isRice: true,
        isPoori: false,
        isBread: false,
        name: "Rice",
        veg: true,
        Qtype: "kg",
        description:
          "Rice is a food that is a part of the plant kingdom and is a member of the class of plants called graminoids.",
        cuisine: "Indian",
      },
      {
        isRice: true,
        isPoori: false,
        isBread: false,
        name: "Rice2",
        veg: true,
        Qtype: "kg",
        description:
          "Rice is a food that is a part of the plant kingdom and is a member of the class of plants called graminoids.",
        cuisine: "Indian",
      },
      {
        isRice: true,
        isPoori: false,
        isBread: false,
        name: "Rice3",
        veg: true,
        Qtype: "kg",
        description:
          "Rice is a food that is a part of the plant kingdom and is a member of the class of plants called graminoids.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: true,
        isBread: true,
        name: "Poori",
        veg: true,
        Qtype: "pcs",
        description: "Poori is a dish made from rice and vegetables.",
        cuisine: "Indian",
      },
      {
        isRice: false,
        isPoori: false,
        isBread: true,
        name: "Naan",
        veg: true,
        Qtype: "pcs",
        description: "Naan is a flatbread made from bread.",
        cuisine: "Indian",
      },
    ],
    desserts: [
      {
        name: "Ice Cream",
        veg: true,
        Qtype: "kg",
        description: "Ice Cream is a dessert that is made from milk.",
        cuisine: "Indian",
      },
      {
        name: "Gulab Jamun",
        veg: true,
        Qtype: "pcs",
        description: "Gulab Jamun is a dessert that is made from milk.",
        cuisine: "Indian",
      },
      {
        name: "Gajar Ka Halwa",
        veg: true,
        Qtype: "kg",
        description: "Gajar Ka Halwa is a dessert that is made from milk.",
        cuisine: "Indian",
      },
    ],
  };

  const allMenus = [
    {
      id: 617,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Achari Paneer Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 260,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Achari+Paneer+Tikka.jpg",
    },
    {
      id: 635,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Amritsari Fish Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Regular",
      selling_price: 325,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Amritsari+Fish+Tikka.jpeg",
    },
    {
      id: 627,
      city: "bangalore",
      menu_label: "Starters ",
      name: "BBQ Chicken Wings",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 255,
      QTY: 12.240000000000002,
      "Garlic Mayo": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/BBQ+Chicken+Wings.jpeg",
    },
    {
      id: 606,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Cajun spice Potato",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 220,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Cajun+Spiced+Potatoes.jpg",
    },
    {
      id: 609,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Cheesy Triangles",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 300,
      QTY: 12.240000000000002,
      "Garlic Mayo": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Cheesy+Triangles+.jpeg",
    },
    {
      id: 632,
      city: "bangalore",
      menu_label: "Starters ",
      name: "chicken seekh kebab  (5.5)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 900,
      QTY: 45,
      "Mint Chutney": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Chicken+Seekh+Kebab.jpeg",
    },
    {
      id: 634,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Achari Chicken Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 255,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Chicken+Tikka+_+Drumstick+Platter.jpg",
    },
    {
      id: 603,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Churasco Pineapple",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 420,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Churasco+Pineapple.jpg",
    },
    {
      id: 628,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Coastal BBQ Fish Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 280,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Coastal+BBQ+Fish+Tikka.jpg",
    },
    {
      id: 607,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Crispy Corn",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 240,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Crispy+Corn.jpg",
    },
    {
      id: 613,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Dahi ke kebab",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 200,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Dahi+k+kebab.jpg",
    },
    {
      id: 625,
      city: "bangalore",
      menu_label: "Starters ",
      name: "French Fries",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 600,
      QTY: 51,
      "Garlic Mayo": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/French+Fries.jpg",
    },
    {
      id: 615,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Gobi Manchurian Dry",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 300,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Gobhi+Manchurian.jpg",
    },
    {
      id: 630,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Chilli Garlic Prawns",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 350,
      QTY: 12.240000000000002,
      "Garlic Mayo": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Grilled+Chilli+Garlic+Prawns.jpg",
    },
    {
      id: 612,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Hara bhara Kebab",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 200,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Hara+bhara+Kebab.jpg",
    },
    {
      id: 602,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Honey chilli Baby Potato",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 260,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Honey+Chilli+Baby+Potato.jpg",
    },
    {
      id: 626,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Kalmi Chicken Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 240,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Kalmi+Chicken+Tikka.jpg",
    },
    {
      id: 608,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Malai Broccoli",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Malai+Broccoli.jpeg",
    },
    {
      id: 619,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Malai Paneer Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 240,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Malai+Paneer+Tikka.jpeg",
    },
    {
      id: 616,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Mushroom Manchurian Dry",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 660,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Mushroom+Manchurian.jpg",
    },
    {
      id: 636,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Mutton Sheekh Kebab",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Regular",
      selling_price: 1600,
      QTY: 45,
      "Mint Chutney": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Mutton+Seekh+Kebab.jpg",
    },
    {
      id: 623,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Paneer Chilly Dry - Classic",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 600,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Paneer+Chilly+Dry+-+Classic.jpg",
    },
    {
      id: 618,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Pudina Paneer Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 260,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Paneer+Pudina+Tikka.webp",
    },
    {
      id: 633,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Pudina Chicken Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 255,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Pudina+Chicken+Tikka.jpg",
    },
    {
      id: 631,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Punjabi Tangdi",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 1000,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Punjabi+Tangdi.jpg",
    },
    {
      id: 601,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Reshmi Mushroom",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 200,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Reshmi+Mushroom.png",
    },
    {
      id: 622,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Schzwan Paneer Chilly Dry",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 600,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Schzwan+Paneer+Chilly+Dry.jpg",
    },
    {
      id: 621,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Tandoori Achari Aloo",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 350,
      QTY: 45,
      "Mint Chutney": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Tandoori+Achari+Aloo.jpg",
    },
    {
      id: 620,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Tandoori Achari Chaap",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 425,
      QTY: 45,
      "Mint Chutney": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Tandoori+Achari+Chaap.jpg",
    },
    {
      id: 629,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Tandoori Fish Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: false,
      mealType: "Starter",
      meal: "Express",
      selling_price: 280,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Tandoori+Fish+Tikka.jpg",
    },
    {
      id: 604,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Tandoori Malai Chap",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 425,
      QTY: 45,
      "Mint Chutney": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Tandoori+Malai+Chap.jpg",
    },
    {
      id: 600,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Tandoori Paneer Tikka",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 260,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Tandoori+Paneer+Tikka.jpg",
    },
    {
      id: 605,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Veg Kebab",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 200,
      QTY: 10.8,
      "Mint Chutney": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Veg+Kababs.jpg",
    },
    {
      id: 614,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Veg Manchurian Dry",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 300,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Veg+Manchurian+Dry.jpg",
    },
    {
      id: 611,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Veg Sheek Kebab",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 450,
      QTY: 45,
      "Mint Chutney": 0.15,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Veg+Sheek+Kebab.jpg",
    },
    {
      id: 610,
      city: "bangalore",
      menu_label: "Starters ",
      name: "Veggie Fingers",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Starter",
      meal: "Express",
      selling_price: 240,
      QTY: 12.240000000000002,
      "Garlic Mayo": 0.036000000000000004,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Starters/Veggie+Fingers.jpeg",
    },
    {
      id: 637,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Tawa Veg",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 420,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/Tawa-Sabzi-fry-recipe-02.jpg",
    },
    {
      id: 638,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Kadai Veg",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 420,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/kadai-vegetables-recipe-2.jpg",
    },
    {
      id: 639,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Aloo Gobi Tamatar",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/Dry+Vegetable+Mix.jpg",
    },
    {
      id: 640,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Jeera Aloo",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/Jeera+aloo.jpg",
    },
    {
      id: 641,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Rajma Masala",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/Rajma+Masala.jpg",
    },
    {
      id: 642,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Chole Masala",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/Chole+Masala.jpg",
    },
    {
      id: 643,
      city: "bangalore",
      menu_label: "Mains-Dry",
      name: "Egg Masala",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Express",
      selling_price: 540,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Dry/Egg+Masala.jpg",
    },
    {
      id: 644,
      city: "bangalore",
      menu_label: "Mains-Dal",
      name: "Dal Makhani",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 460,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Dal/Dal+Makhani.jpg",
    },
    {
      id: 645,
      city: "bangalore",
      menu_label: "Mains-Dal",
      name: "Yellow Dal Fry",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Dal/Dal+Fry.jpg",
    },
    {
      id: 646,
      city: "bangalore",
      menu_label: "Mains-Dal",
      name: "Dal Tadka",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Dal/Tadkewali+dal.JPG",
    },
    {
      id: 647,
      city: "bangalore",
      menu_label: "Mains-Paneer",
      name: "Paneer Butter masala",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 720,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Paneer/Paneer+Butter+Masala.jpg",
    },
    {
      id: 648,
      city: "bangalore",
      menu_label: "Mains-Paneer",
      name: "Paneer Kadai",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 720,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Paneer/Kadai+Paneer.jpg",
    },
    {
      id: 649,
      city: "bangalore",
      menu_label: "Mains-Paneer",
      name: "Paneer Lababdar",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 720,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Paneer/Paneer+Lababdar.jpg",
    },
    {
      id: 656,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Butter chicken masala",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Express",
      selling_price: 900,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Butter+Chicken.jpg",
    },
    {
      id: 659,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Chicken Kadai",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 800,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Chicken+Kadahi.jpg",
    },
    {
      id: 660,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Chicken Lababdar",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 800,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Chicken+Lababdar.jpg",
    },
    {
      id: 668,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Chicken Manchurian Gravy - Chilli Garlic sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 840,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Chicken+manchurian+Gravy.jpg",
    },
    {
      id: 669,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Chicken Manchurian Gravy - Schezwan Sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 840,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Chicken+Manchurian+in+hunan+sauce.jpg",
    },
    {
      id: 652,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Chilli Chicken with Bone ",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Express",
      selling_price: 800,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Chilli+Garlic+Chicken+in+Shchezwan++Sauce.jpg",
    },
    {
      id: 672,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Prawns in Chilli Garlic sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 1500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Chilli-Garlic-Prawns-1_5.webp",
    },
    {
      id: 657,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Fish curry",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Express",
      selling_price: 840,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/fish+curry.jpg",
    },
    {
      id: 671,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Fish in Schezwan sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 1000,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/fish+in+chilli+garlic+sauce.jpg",
    },
    {
      id: 670,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Fish in Chilli Garlic sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 1000,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Fish+In+hunan+Sauce.jpg",
    },
    {
      id: 654,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Malai Kofta Gravy",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 560,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Malai+Kofta+Curry.jpg",
    },
    {
      id: 662,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Malabar/Kerala Fish Curry ",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 1000,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/malbarkerlafish.jpg",
    },
    {
      id: 663,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Mutton Gravy(with bone) - Kosha",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 1500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Mutton+Kosha.webp",
    },
    {
      id: 658,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Mutton Rogan Josh",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Express",
      selling_price: 1200,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Mutton+Rogan+Josh.jpg",
    },
    {
      id: 655,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Paneer Kofta Gravy",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 560,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Paneer+Kofta+curry.jpg",
    },
    {
      id: 667,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Paneer Manchurian Gravy",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 660,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/paneer+manchurian+garvy.jpg",
    },
    {
      id: 661,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Punjabi Chicken Curry",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 800,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Punjabi+Chicken+Curry(With+Bone).jpg",
    },
    {
      id: 650,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Sabz E Bahar",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 420,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/sabz+e+bahar.jpg",
    },
    {
      id: 673,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Prawns in Chilli Schezwan sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 1500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/stir+fried+prawns.webp",
    },
    {
      id: 653,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Veg Kofta Curry",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Veg+Kofta+Curry.jpg",
    },
    {
      id: 651,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Veg Manchurian Gravy",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/_Veg+Manchurian+Gravy.jpg",
    },
    {
      id: 665,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Veg Manchurian Gravy - Schezwan Sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/Veg+manchurian+In+schezuan+sauce.jpg",
    },
    {
      id: 666,
      city: "bangalore",
      menu_label: "Mains-Gravy",
      name: "Veg Manchurian Gravy - Chilli Garlic Sauce",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Mains-Gravy/veg-manchurian.jpg",
    },
    {
      id: 774,
      city: "bangalore",
      menu_label: "Pasta",
      name: "Arabiata Pasta (Tomota Sauce)",
      Qtype: "kg",
      cuisine: "Continental",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Pasta/Pasta+Arabiatta.jpg",
    },
    {
      id: 775,
      city: "bangalore",
      menu_label: "Pasta",
      name: "Alfredo Pasta (White Sauce)",
      Qtype: "kg",
      cuisine: "Continental",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 440,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Pasta/Pasta+Alfredo.jpg",
    },
    {
      id: 776,
      city: "bangalore",
      menu_label: "Pasta",
      name: "Veg Mac N Cheese Pasta",
      Qtype: "kg",
      cuisine: "Continental",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Pasta/Mac+N+cheese.jpg",
    },
    {
      id: 675,
      city: "bangalore",
      menu_label: "Pasta",
      name: "Chicken Mac-n-Cheese Pasta",
      Qtype: "kg",
      cuisine: "Continental",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 660,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Pasta/chicken+mac+n+cheese.jpg",
    },
    {
      id: 676,
      city: "bangalore",
      menu_label: "Pasta",
      name: "Chicken Arabiata Pasta (Tomota Sauce)",
      Qtype: "kg",
      cuisine: "Continental",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 660,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Pasta/chicken_arrabiata.jpg",
    },
    {
      id: 677,
      city: "bangalore",
      menu_label: "Pasta",
      name: "Chicken Alfredo Pasta (White Sauce)",
      Qtype: "kg",
      cuisine: "Continental",
      veg: false,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 660,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Pasta/Pasta+Alfredo-+Chicken.jpg",
    },
    {
      id: 678,
      city: "bangalore",
      menu_label: "Heavy Snack",
      name: "Chicken Keema (1 Kg includes 20 Pav)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Main course",
      meal: "Express",
      selling_price: 1400,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Heavy+Snacks/Kheema-Pav-6.jpg",
    },
    {
      id: 679,
      city: "bangalore",
      menu_label: "Heavy Snack",
      name: "Pav Bhaji (1 Kg includes 20 Pav)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 900,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Heavy+Snacks/Pav+Bhaji.jpg",
    },
    {
      id: 680,
      city: "bangalore",
      menu_label: "Heavy Snack",
      name: "Extra Pav",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Regular",
      selling_price: 240,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Heavy+Snacks/pav-buns-recipe.jpg",
    },
    {
      id: 681,
      city: "bangalore",
      menu_label: "Sides",
      name: "Mix Veg Salad ",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 120,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Sides/Kachumber-salad-1.jpg",
    },
    {
      id: 682,
      city: "bangalore",
      menu_label: "Sides",
      name: "Raita",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 220,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Sides/Boondi-Raita.webp",
    },
    {
      id: 683,
      city: "bangalore",
      menu_label: "Sides",
      name: "Plain Curd",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 180,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Sides/plain+curd.webp",
    },
    {
      id: 684,
      city: "bangalore",
      menu_label: "Sides",
      name: "Salad",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Main course",
      meal: "Express",
      selling_price: 300,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Sides/Salan.jpg",
    },
    {
      id: 690,
      city: "bangalore",
      menu_label: "Rice",
      name: "Chicken Seekh Dum Biryani (Includes Raita)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 665,
      Raita: 0.2,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Boneless+Chicken+Biryani.jpg",
    },
    {
      id: 685,
      city: "bangalore",
      menu_label: "Rice",
      name: "Chicken Dum Biryani (Includes Raita)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 585,
      Raita: 0.2,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Chicken+Biryani.jpg",
    },
    {
      id: 708,
      city: "bangalore",
      menu_label: "Rice",
      name: "Chicken Fried Rice",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 620,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Chicken+Fried+Rice.png",
    },
    {
      id: 709,
      city: "bangalore",
      menu_label: "Rice",
      name: "Chicken Schezwan Rice",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 620,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Chicken+Schezwan+Rice.jpg",
    },
    {
      id: 691,
      city: "bangalore",
      menu_label: "Rice",
      name: "Curd Rice",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 220,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Curd+Rice.webp",
    },
    {
      id: 693,
      city: "bangalore",
      menu_label: "Rice",
      name: "Flavoured Rice / Veg Pulao",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 340,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Flavoured+Rice.jpg",
    },
    {
      id: 686,
      city: "bangalore",
      menu_label: "Rice",
      name: "Mutton Dum Biryani (Includes Raita)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 765,
      Raita: 0.2,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Mutton+Biryani.jpg",
    },
    {
      id: 688,
      city: "bangalore",
      menu_label: "Rice",
      name: "Paneer Tikka Dum Biryani (Includes Raita)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 465,
      Raita: 0.2,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Paneer+Tikka+Biryani.jpg",
    },
    {
      id: 689,
      city: "bangalore",
      menu_label: "Rice",
      name: "Prawns Biryani (Includes Raita)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 1150,
      Raita: 0.2,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Prawns+Biryani.jpg",
    },
    {
      id: 694,
      city: "bangalore",
      menu_label: "Breads",
      name: "Butter Naan",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 480,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Breads/Butter+Naan.jpg",
    },
    {
      id: 695,
      city: "bangalore",
      menu_label: "Breads",
      name: "Lachha Paratha",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 480,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Breads/Paratha+(1+No).jpg",
    },
    // {
    //   id: 696,
    //   city: "bangalore",
    //   menu_label: "Breads",
    //   name: "Plain Naan",
    //   Qtype: "pcs",
    //   cuisine: "Indian",
    //   veg: true,
    //   mealType: "Bread+Rice",
    //   meal: "Express",
    //   selling_price: 360,
    //   Images:
    //     "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Breads/Butter+Naan+(1No).jpg",
    // },
    {
      id: 697,
      city: "bangalore",
      menu_label: "Breads",
      name: 'Poori - 4',
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Regular",
      selling_price: 120,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Breads/Pooris.jpg",
    },
    {
      id: 698,
      city: "bangalore",
      menu_label: "Breads",
      name: "Wheat Paratha",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Regular",
      selling_price: 480,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Breads/Plain+Naan.jpeg",
    },
    {
      id: 699,
      city: "bangalore",
      menu_label: "Breads",
      name: "Butter Tandoori Kulcha",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Regular",
      selling_price: 480,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Breads/Butter+Garlic+Naan.jpg",
    },
    {
      id: 700,
      city: "bangalore",
      menu_label: "Noodle",
      name: "Veg Hakka Noodle",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Noodles/Veg-Hakka-Noodles.jpg",
    },
    {
      id: 701,
      city: "bangalore",
      menu_label: "Noodle",
      name: "Veg Chilli Garlic Noodle",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Noodles/Veg+Chilli+Garlic+Noodle.jpg",
    },
    {
      id: 702,
      city: "bangalore",
      menu_label: "Noodle",
      name: "Veg Schezwan Noodle",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Noodles/Veg+Schezwan+Noodle.webp",
    },
    {
      id: 704,
      city: "bangalore",
      menu_label: "Rice",
      name: "Veg Schezwan Rice",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Schezwan+Fried+Rice.jpg",
    },
    {
      id: 692,
      city: "bangalore",
      menu_label: "Rice",
      name: "Steamed Rice",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 340,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Steamed+Basmati+Rice.jpg",
    },
    {
      id: 705,
      city: "bangalore",
      menu_label: "Noodle",
      name: "Chicken Hakka Noodle",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 620,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Noodles/Chicken+Hakka+Noodle.jpg",
    },
    {
      id: 706,
      city: "bangalore",
      menu_label: "Noodle",
      name: "Chicken Chilli Noodle",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 620,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Noodles/Chicken+Chilli+Noodle.webp",
    },
    {
      id: 707,
      city: "bangalore",
      menu_label: "Noodle",
      name: "Chicken Schezwan Noodle",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: false,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 620,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Noodles/Chicken+Schezwan+Noodles.jpg",
    },
    {
      id: 687,
      city: "bangalore",
      menu_label: "Rice",
      name: "Veg Dum Biryani (Includes Raita)",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 385,
      Raita: 0.2,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Veg+Biryani.jpg",
    },
    {
      id: 703,
      city: "bangalore",
      menu_label: "Rice",
      name: "Veg Fried Rice",
      Qtype: "kg",
      cuisine: "Pan Asian",
      veg: true,
      mealType: "Bread+Rice",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Rice/Veg+Fried+Rice.jpg",
    },
    {
      id: 715,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Angoori Gulab Jamun",
      Qtype: "pcs",
      cuisine: "Indian",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 96,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/Angoori+Jamun+(12+Nos).jpg",
    },
    {
      id: 710,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Chocolate Brownie",
      Qtype: "pcs",
      cuisine: "Continental",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/Chocolate+Brownie.jpg",
    },
    {
      id: 713,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Fruit custard",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 440,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/Indian-fruit-custard-recipe.jpg",
    },
    {
      id: 717,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Kesariya Phirni",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 280,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/Kesar-Phirni.jpg",
    },
    {
      id: 714,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Moong Dal Halwa",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 520,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/Moong+Dal+Halwa.jpg",
    },
    {
      id: 712,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Pineapple Pastry",
      Qtype: "pcs",
      cuisine: "Continental",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 130,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/pineapple+pastry.jpg",
    },
    {
      id: 716,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Paysam",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 260,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/Semiyan-Payasam.jpg",
    },
    {
      id: 718,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Shahi meetha",
      Qtype: "kg",
      cuisine: "Indian",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 500,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/shahi+Tukda.jpg",
    },
    {
      id: 711,
      city: "bangalore",
      menu_label: "Dessert",
      name: "Chocolate Pastry",
      Qtype: "pcs",
      cuisine: "Continental",
      veg: true,
      mealType: "Dessert",
      meal: "Express",
      selling_price: 360,
      Images:
        "https://caterninjacdn.s3.amazonaws.com/DIY Image/DIY+Desserts/TheosEgglessDutchTrufflePastry1.webp",
    },
  ];

  var cuisines = [
    "All",
    "Pan Asian",
    "Indian",
    // "Bengali",
    // "Chinese",
    // "French",
    // "Japanese"
  ];
  var cities = [
    "Mumbai",
    "Thane",
    "Navi-Mumbai",
    "Pune",
    "Bangalore",
    "Chennai",
    // "Hyderabad",
    "Delhi",
    "Gurgaon",
    "Noida",
    "Ghaziabad",
  ];
  var occasions = [
    "Birthday",
    "House Party",
    "Pooja @ Home",
    "Pre-Wedding",
    "Office Party",
    "House Warming",
    "Kitty Party",
    "Kids Party",
    "Baby Shower",
    "Anniversary",
    "Inviting Guests",
    "Festivals",
    "Others",
  ];

  var PreSelectMenuNinjaBox = {
    veg: [
      { id: 1, name: 'Punjabi Party', price: 2599,  img: '/ninja-box/packages/NBP-1.png', details: "1 Starters + 4 Mains + 0 Dessert", items: ["Tandoori Achari Aloo", "Chole Masala", "Dal Makhani", "Steamed Rice", "Lachha Paratha"] },
      { id: 2, name: 'Indian Party', price: 3099,  img: '/ninja-box/packages/NBP2.png', details: "0 Starters + 5 Mains + 1 Dessert", items: ["Paneer Butter masala", "Dal Makhani", "Kadai Veg", "Lachha Paratha", "Steamed Rice", "Angoori Gulab Jamun"] },
      { id: 3, name: 'Asian Party', price: 2399,  img: '/ninja-box/packages/NBP2.png', details: "2 Starters + 3 Mains + 1 Dessert", items: ["Honey chilli Baby Potato", "Crispy Corn", "Veg Manchurian Gravy", "Veg Fried Rice", "Chocolate Pastry"] }, 
      {
        id: 4,
        name: "Cocktail Party 1",
        price: 3099,
        img: "/ninja-box/packages/NBP4.png",
        details: "5 Starters + 1 Mains + 1 Dessert",
        items: [
          "Cheesy Triangles",
          "Achari Paneer Tikka",
          "Veggie Fingers",
          "Veg Sheek Kebab",
          "Cajun spice Potato",
          "Veg Dum Biryani (Includes Raita)",
          "Chocolate Pastry"
          
        ],
      },
      {
        id: 5,
        name: "Cocktail Party 2",
        price: 2699,
        img: "/ninja-box/packages/NBP5.png",
        details: "1 Starters + 3 Mains + 1 Dessert",
        items: [
          "French Fries",
          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Veg Mac N Cheese Pasta",
          "Veg Hakka Noodle",
          "Chocolate Pastry"
          
        ],
      },
      {
        id: 6,
        name: "House Party",
        price: 3399,
        img: "/ninja-box/packages/NBP6.png",
        details: "2 Starters + 4 Mains + 1 Dessert",
        items: [
          "French Fries",
          "Crispy Corn",
          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Veg Mac N Cheese Pasta",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Veg Hakka Noodle",
          "Angoori Gulab Jamun"
        ],
      },
      {
        id: 7,
        name: "Punjabi Party",
        price: 4599,
        img: "/ninja-box/packages/NBP4.png",
        details: "2 Starters + 5 Mains + 1 Dessert",
        items: [
          "Achari Paneer Tikka",
          "Hara bhara Kebab",
          "Paneer Lababdar",
          "Veg Kofta Curry",
          "Dal Makhani", 
          "Steamed Rice",
          "Lachha Paratha",
          "Moong Dal Halwa",
        ],
      },
      {
        id: 8,
        name: "Indian Party",
        price: 3999,
        img: "/ninja-box/packages/NBP5.png",
        details: "2 Starters + 5 Mains + 1 Dessert",
        items: [
          "Paneer Chilly Dry - Classic",
          "Crispy Corn",
          "Paneer Butter masala",
          "kadai Veg",
          "Dal Makhani", 
          "Steamed Rice",
          "Lachha Paratha",
          "Kesariya Phirni",
        ],
      },
      {
        id: 9,
        name: "Asian party",
        price: 3599,
        img: "/ninja-box/packages/NBP5.png",
        details: "3 Starters + 5 Mains + 1 Dessert",
        items: [
          "Crispy Corn",
          "Churasco Pineapple",
          "Honey chilli Baby Potato",
          "Veg Fried Rice",
          "Veg Hakka Noodle",
          "Veg Chilli Garlic Noodle",
          "Paneer Manchurian Gravy",
          "Veg Manchurian Gravy",
          "Chocolate Brownie"
          
        ],
      },
      {
        id: 10,
        name: "Cocktail Party 1",
        price: 4099,
        img: "/ninja-box/packages/NBP5.png",
        details: "6 Starters + 1 Mains + 1 Dessert",
        items: [
          "Cheesy Triangles",
          "Achari Paneer Tikka",
          "Veggie Fingers",
          "Hara bhara Kebab",
          "Honey chilli Baby Potato",
          "Veg Manchurian Dry",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Shahi meetha"
          
        ],
      },
      {
        id: 11,
        name: "Cocktail Party 2",
        price: 3899,
        img: "/ninja-box/packages/NBP5.png",
        details: "3 Starters + 5 Mains + 1 Dessert",
        items: [
          "French Fries",
          "Crispy Corn",
          "Cheesy Triangles",

          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Veg Mac N Cheese Pasta",
          "Arabiata Pasta (Tomota Sauce)",
          "Veg Hakka Noodle",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie"
          
        ],
      },
      {
        id: 12,
        name: "House Party",
        price: 4799,
        img: "/ninja-box/packages/NBP5.png",
        details: "4 Starters + 5 Mains + 2 Dessert",
        items: [
          "Tandoori Paneer Tikka",
          "Tandoori Achari Aloo",
          "French Fries",
          "Crispy Corn",
          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Veg Mac N Cheese Pasta",
          "Arabiata Pasta (Tomota Sauce)",
          "Veg Schezwan Noodle",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Pineapple Pastry",

          
        ],
      },
      {
        id: 13,
        name: "Punjabi Party",
        price: 6099,
        img: "/ninja-box/packages/NBP5.png",
        details: "4 Starters + 6 Mains + 2 Dessert",
        items: [
          "Achari Paneer Tikka",
          "Tandoori Achari Aloo",
          "Cheesy Triangles",
          "Hara bhara Kebab",
          "Paneer Lababdar",
          "Veg Kofta Curry",
          "Tawa Veg",
          "Dal Makhani", 
          "Lachha Paratha",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Angoori Gulab Jamun"

          
        ],
      },
      {
        id: 14,
        name: "Indian Party",
        price: 5399,
        img: "/ninja-box/packages/NBP5.png",
        details: "4 Starters + 5 Mains + 2 Dessert",
        items: [
          "Paneer Chilly Dry - Classic",
          "Crispy Corn",
          "Honey chilli Baby Potato",
          "Veg Manchurian Dry",
          "Paneer Butter masala",
          "kadai Veg",
          "Dal Makhani", 
          "Steamed Rice",
          "Lachha Paratha",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Shahi meetha"
        ],
      },
      {
        id: 15,
        name: "Asian Party",
        price: 5099,
        img: "/ninja-box/packages/NBP5.png",
        details: "5 Starters + 5 Mains + 2 Dessert",
        items: [
          "Crispy Corn",
          "Honey chilli Baby Potato",
          "Churasco Pineapple",
          "Mushroom Manchurian Dry",
          "Schzwan Paneer Chilly Dry",
          "Veg Manchurian Gravy",
          "Paneer Manchurian Gravy",
          "Veg Fried Rice",
          "Veg Hakka Noodle",
          "Veg Chilli Garlic Noodle",
          "Angoori Gulab Jamun",
          "Chocolate Brownie",
        ],
      },
      {
        id: 16,
        name: "Cocktail Party 1",
        price: 5099,
        img: "/ninja-box/packages/NBP5.png",
        details: "5 Starters + 4 Mains + 2 Dessert",
        items: [
          "Cheesy Triangles",
          "Achari Paneer Tikka",
          "Veggie Fingers",
          "Veg Kebab",
          "Malai Broccoli",
          "Veg Manchurian Gravy",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Veg Fried Rice",
          "Veg Schezwan Noodle",
          "Chocolate Brownie",
          "Moong Dal Halwa",
        ],
      },
      {
        id: 17,
        name: "Cocktail Party 2",
        price: 6099,
        img: "/ninja-box/packages/NBP5.png",
        details: "5 Starters + 5 Mains + 2 Dessert",
        items: [
          "French Fries",
          "Crispy Corn",
          "Cheesy Triangles",
          "Tandoori Paneer Tikka",
          "Tandoori Malai Chap",
          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Veg Mac N Cheese Pasta",
          "Arabiata Pasta (Tomota Sauce)",
          "Veg Hakka Noodle",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Moong Dal Halwa",
          
        ],
      },
      {
        id: 18,
        name: "House Party",
        price: 5699,
        img: "/ninja-box/packages/NBP5.png",
        details: "5 Starters + 5 Mains + 2 Dessert",
        items: [
          "Pudina Paneer Tikka",
          "Tandoori Achari Aloo",
          "Cheesy Triangles",
          "Hara bhara Kebab",
          "Malai Broccoli", 
          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Alfredo Pasta (White Sauce)",
          "Arabiata Pasta (Tomota Sauce)",
          "Veg Schezwan Noodle",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Moong Dal Halwa",
        ],
      },
    ],
    nonVeg: [
      {
        id: 1,
        name: "Punjabi Party",
        price: 3499,
        img: "/ninja-box/packages/NBP-1.png",
        details: "1 Starters + 4 Mains",
        items: [
          "Achari Chicken Tikka",          
          "Butter chicken masala",
          "Dal Makhani",
          "Steamed Rice",
          "Lachha Paratha",
        ],
      },
      {
        id: 2,
        name: "Indian Party",
        price: 2999,
        img: "/ninja-box/packages/NBP2.png",
        details: "5 Mains",
        items: [
          "Dal Makhani",
          "Chicken Kadai",
          "Tawa Veg",
          "Lachha Paratha",
          "Steamed Rice",
        ],
      },
      {
        id: 3,
        name: "Asian Party",
        price: 2799,
        img: "/ninja-box/packages/NBP3.png",
        details: "2 Starters + 3 Mains",
        items: [
          "BBQ Chicken Wings",
          "Honey chilli Baby Potato",
          "Veg Manchurian Gravy",
          "Chicken Fried Rice",
          "Veg Hakka Noodle",
        
        ],
      },
      {
        id: 4,
        name: "Cocktail Party 1",
        price: 2399,
        img: "/ninja-box/packages/NBP4.png",
        details: "4 Starters + 2 Mains",
        items: [
          "BBQ Chicken Wings",
          "Achari Paneer Tikka",
          "Dahi ke kebab",
          "Tandoori Fish Tikka",
          "Chicken Seekh Dum Biryani (Includes Raita)",
          "Veg Dum Biryani (Includes Raita)",
        ],
      },
      {
        id: 5,
        name: "Cocktail Party 2",
        price: 2699,
        img: "/ninja-box/packages/NBP5.png",
        details: "1 Starters + 4 Mains + 1 Dessert",
        items: [
          "French Fries",
          "Chicken Alfredo Pasta (White Sauce)",
          "Arabiata Pasta (Tomota Sauce)",
          "Veg Hakka Noodle",
          "Veg Dum Biryani (Includes Raita)",
          "Chocolate Pastry"
        ],
      },
      {
        id: 6,
        name: "House Party",
        price: 3299,
        img: "/ninja-box/packages/NBP6.png",
        details: "5 Mains",
        items: [
          "Chicken Keema (1 Kg includes 20 Pav)",
          "Arabiata Pasta (Tomota Sauce)",
          "Chicken Dum Biryani (Includes Raita)",
          "Veg Dum Biryani (Includes Raita)",
          "Veg Hakka Noodle",
        ],
      },
      {
        id: 7,
        name: "Punjabi Party",
        price: 3899,
        img: "/ninja-box/packages/NBP-1.png",
        details: "2 Starters + 5 Mains + 1 Dessert",
        items: [
          "Tandoori Achari Aloo", 
          "Coastal BBQ Fish Tikka",         
          "Butter chicken masala",
          "Kadai Veg",
          "Dal Makhani",
          "Steamed Rice",
          "Lachha Paratha",
          "Chocolate Pastry"
        ],
      },
      {
        id: 8,
        name: "Indian Party",
        price: 4299,
        img: "/ninja-box/packages/NBP2.png",
        details: "2 Starters + 5 Mains + 1 Dessert",
        items: [
          "Achari Chicken Tikka",
          "Honey chilli Baby Potato",
          "Dal Makhani",
          "Chicken Kadai",
          "Paneer Lababdar",
          "Lachha Paratha",
          "Steamed Rice",
          "Kesariya Phirni"
        ],
      },
      {
        id: 9,
        name: "Asian Party",
        price: 4099,
        img: "/ninja-box/packages/NBP3.png",
        details: "2 Starters + 4 Mains + 1 Dessert",
        items: [
          "Chilli Garlic Prawns",
          "Churasco Pineapple",
          "Chicken Manchurian Gravy",
          "Veg Manchurian Gravy",
          "Chicken Fried Rice",
          "Veg Hakka Noodle",
          "Chocolate Brownie",
        
        ],
      },
      {
        id: 10,
        name: "Cocktail Party 1",
        price: 4299,
        img: "/ninja-box/packages/NBP4.png",
        details: "5 Starters + 2 Mains + 1 Dessert",
        items: [
          "BBQ Chicken Wings",
          "Tandoori Fish Tikka",
          "Chilli Garlic Prawns",
          "Tandoori Achari Aloo",
          "Hara bhara Kebab",
          "Chicken Seekh Dum Biryani (Includes Raita)",
          "Paneer Tikka Biryani (Includes Raita)",
          "Moong Dal Halwa"
        ],
      },
      {
        id: 11,
        name: "Cocktail Party 2",
        price: 4199,
        img: "/ninja-box/packages/NBP5.png",
        details: "1 Starters + 5 Mains + 1 Dessert",
        items: [
          "French Fries",
          "Veg Mac N Cheese Pasta",
          "Chicken Keema (1 Kg includes 20 Pav)",
          "Veg Hakka Noodle",
          "Chicken Seekh Dum Biryani (Includes Raita)",
          "Paneer Tikka Biryani (Includes Raita)",
          "Pineapple Pastry"
        ],
      },
      {
        id: 12,
        name: "House Party",
        price: 4799,
        img: "/ninja-box/packages/NBP6.png",
        details: "6 Mains + 1 Dessert",
        items: [
          "Chicken Keema (1 Kg includes 20 Pav)",
          "Fish in Schezwan sauce",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Mutton Dum Biryani (Includes Raita)",
          "Chicken Dum Biryani (Includes Raita)",
          "Veg Fried Rice",
          "Veg Schezwan Noodle",
          "Chocolate Brownie",
        ],
      },
      {
        id: 13,
        name: "Punjabi Party",
        price: 5199,
        img: "/ninja-box/packages/NBP-1.png",
        details: "3 Starters + 5 Mains + 1 Dessert",
        items: [
          "Achari Chicken Tikka",   
          "Amritsari Fish Tikka",   
          "Chilli Garlic Prawns",    
          "Butter chicken masala",
          "Dal Makhani",
          "Malai Kofta Gravy",
          "Steamed Rice",
          "Lachha Paratha",
          "Chocolate Brownie"
        ],
      },
      {
        id: 14,
        name: "Indian Party",
        price: 5499,
        img: "/ninja-box/packages/NBP2.png",
        details: "6 Mains + 2 Dessert",
        items: [
          "Dal Makhani",
          "Chicken Kadai",
          "Mutton Rogan Josh",
          "Paneer Lababdar",
          "Lachha Paratha",
          "Veg Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Fruit Custard"
        ],
      },
      {
        id: 15,
        name: "Asian Party",
        price: 6499,
        img: "/ninja-box/packages/NBP3.png",
        details: "3 Starters + 5 Mains + 2 Dessert",
        items: [
          "chicken seekh kebab  (5.5)",
          "Tandoori Paneer Tikka",
          "Mutton Sheekh Kebab",
          "Veg Manchurian Gravy",
          "Chicken Fried Rice",
          "Veg Fried Rice",
          "Veg Hakka Noodle",
          "Chicken Manchurian Gravy - Chilli Garlic sauce",
          "Chocolate Pastry",
          "Moong Dal Halwa"
        ],
      },
      {
        id: 16,
        name: "Cocktail Party",
        price: 5699,
        img: "/ninja-box/packages/NBP4.png",
        details: "2 Starters + 5 Mains + 2 Dessert",
        items: [
          "BBQ Chicken Wings",
          "Achari Paneer Tikka",
          "Prawns in Chilli Garlic sauce",
          "Fish in Schezwan sauce",
          "Veg Manchurian Gravy",
          "Veg Fried Rice",
          "Veg Hakka Noodle",
          "Chocolate Brownie",
          "Pineapple Pastry"
        ],
      },
      {
        id: 17,
        name: "Cocktail Party 2",
        price: 5899,
        img: "/ninja-box/packages/NBP5.png",
        details: "6 Starters + 2 Mains + 2 Dessert",
        items: [
          "Chilli Garlic Prawns",
          "Tandoori Fish Tikka",
          "Tandoori Achari Aloo",
          "BBQ Chicken Wings",
          "Mutton Sheekh Kebab",
          "Hara bhara Kebab",
          "Mutton Dum Biryani (Includes Raita)",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chocolate Brownie",
          "Kesariya Phirni"
        ],
      },
      {
        id: 18,
        name: "House Party",
        price: 5799,
        img: "/ninja-box/packages/NBP6.png",
        details: "1 Starters + 6 Mains + 2 Dessert",
        items: [
          "French Fries",
          "Chicken Keema (1 Kg includes 20 Pav)",
          "Pav Bhaji (1 Kg includes 20 Pav)",
          "Veg Mac N Cheese Pasta",
          "Mutton Dum Biryani (Includes Raita)",
          "Paneer Tikka Dum Biryani (Includes Raita)",
          "Chicken Hakka Noodle",
          "Chocolate Brownie",
          "Pineapple Pastry",
          
        ],
      },


    ],
  };

  var ZipCodes = [
    "400001",
    "400002",
    "400003",
    "400004",
    "400005",
    "400006",
    "400007",
    "400008",
    "400009",
    "400010",
    "400011",
    "400012",
    "400013",
    "400014",
    "400015",
    "400016",
    "400017",
    "400018",
    "400019",
    "400020",
    "400021",
    "400022",
    "400024",
    "400025",
    "400026",
    "400027",
    "400028",
    "400029",
    "400030",
    "400031",
    "400032",
    "400033",
    "400034",
    "400035",
    "400036",
    "400037",
    "400042",
    "400043",
    "400049",
    "400050",
    "400051",
    "400052",
    "400053",
    "400054",
    "400055",
    "400056",
    "400057",
    "400058",
    "400059",
    "400060",
    "400061",
    "400063",
    "400064",
    "400065",
    "400066",
    "400067",
    "400068",
    "400069",
    "400070",
    "400071",
    "400072",
    "400074",
    "400075",
    "400076",
    "400077",
    "400078",
    "400079",
    "400080",
    "400081",
    "400082",
    "400083",
    "400084",
    "400085",
    "400086",
    "400087",
    "400088",
    "400089",
    "400091",
    "400092",
    "400093",
    "400094",
    "400095",
    "400096",
    "400097",
    "400098",
    "400099",
    "400101",
    "400102",
    "400103",
    "400104",
    "400601",
    "400602",
    "400603",
    "400604",
    "400605",
    "400606",
    "400607",
    "400608",
    "400610",
    "400612",
    "400615",
    "401101",
    "401105",
    "401106",
    "401107",
    "401206",
    "421101",
    "421302",
    "421305",
    "421308",
    "421311",
    "421312",
    "421004",
    "421102",
    "421201",
    "421202",
    "421203",
    "421204",
    "421301",
    "421306",
    "421605",
    "400614",
    "400701",
    "400703",
    "400706",
    "400708",
    "400710",
    "411014",
    "411040",
    "411032",
    "411035",
    "411003",
    "411027",
    "411026",
    "411039",
    "411037",
    "411001",
    "411031",
    "411062",
    "411019",
    "411033",
    "411012",
    "411012",
    "411015",
    "411015",
    "411001",
    "411014",
    "411003",
    "411001",
    "411028",
    "411003",
    "411028",
    "411013",
    "411032",
    "411026",
    "411057",
    "411033",
    "411017",
    "411034",
    "411003",
    "411003",
    "411048",
    "411048",
    "411048",
    "411047",
    "411019",
    "411037",
    "411057",
    "411018",
    "411060",
    "411036",
    "411036",
    "411048",
    "411001",
    "411018",
    "411044",
    "411061",
    "411017",
    "411018",
    "411017",
    "411033",
    "411001",
    "411001",
    "411001",
    "411062",
    "411001",
    "411037",
    "411027",
    "411028",
    "411022",
    "411037",
    "411062",
    "411033",
    "411033",
    "411014",
    "411032",
    "411014",
    "411015",
    "411057",
    "411040",
    "411044",
    "411006",
    "411006",
    "411004",
    "411046",
    "411051",
    "411021",
    "411007",
    "411007",
    "411002",
    "411045",
    "411008",
    "411021",
    "411042",
    "411038",
    "411020",
    "411005",
    "411004",
    "411043",
    "411041",
    "411038",
    "411004",
    "411007",
    "411042",
    "411016",
    "411016",
    "411042",
    "411002",
    "411052",
    "411011",
    "411046",
    "411024",
    "411038",
    "411023",
    "411030",
    "411023",
    "411011",
    "411016",
    "411008",
    "411023",
    "411045",
    "411002",
    "411041",
    "411030",
    "411052",
    "411009",
    "411009",
    "411002",
    "411020",
    "411030",
    "411011",
    "411002",
    "411030",
    "411005",
    "411030",
    "411030",
    "411016",
    "411005",
    "411023",
    "411002",
    "411041",
    "411021",
    "411042",
    "411042",
    "411023",
    "411041",
    "411058",
    "413104",
    "110002",
    "110055",
    "110002",
    "110005",
    "110005",
    "110005",
    "110001",
    "110001",
    "110001",
    "110001",
    "110001",
    "110008",
    "110002",
    "110003",
    "110003",
    "110005",
    "110001",
    "110002",
    "110005",
    "110006",
    "110012",
    "110002",
    "110012",
    "110002",
    "110006",
    "110001",
    "110005",
    "110001",
    "110001",
    "110005",
    "110002",
    "110055",
    "110012",
    "110011",
    "110001",
    "110055",
    "110003",
    "110001",
    "110008",
    "110008",
    "110008",
    "110008",
    "110001",
    "110001",
    "110001",
    "110001",
    "110060",
    "110004",
    "110001",
    "110001",
    "110005",
    "110001",
    "110001",
    "110011",
    "110001",
    "110055",
    "110011",
    "110069",
    "110001",
    "110020",
    "110029",
    "110092",
    "110051",
    "110032",
    "110032",
    "110091",
    "110032",
    "110031",
    "110031",
    "110031",
    "110032",
    "110051",
    "110091",
    "110092",
    "110031",
    "110091",
    "110091",
    "110051",
    "110092",
    "110032",
    "110032",
    "110092",
    "110091",
    "110096",
    "110092",
    "110091",
    "110031",
    "110031",
    "110051",
    "110032",
    "110032",
    "110032",
    "110092",
    "110031",
    "110032",
    "110092",
    "110032",
    "110091",
    "110096",
    "110032",
    "110092",
    "110006",
    "110054",
    "110085",
    "110006",
    "110007",
    "110006",
    "110006",
    "110054",
    "110006",
    "110006",
    "110007",
    "110054",
    "110007",
    "110007",
    "110007",
    "110054",
    "110007",
    "110007",
    "110054",
    "110007",
    "110007",
    "110007",
    "110007",
    "110006",
    "110007",
    "110054",
    "110025",
    "110062",
    "110019",
    "110076",
    "110003",
    "110024",
    "110049",
    "110062",
    "110003",
    "110020",
    "110019",
    "110062",
    "110062",
    "110062",
    "110013",
    "110024",
    "110062",
    "110017",
    "110062",
    "110065",
    "110049",
    "110003",
    "110048",
    "110049",
    "110062",
    "110014",
    "110013",
    "110025",
    "110014",
    "110014",
    "110048",
    "110019",
    "110003",
    "110062",
    "110024",
    "110024",
    "110003",
    "110076",
    "110048",
    "110017",
    "110065",
    "110019",
    "110049",
    "110025",
    "110020",
    "110020",
    "110017",
    "110003",
    "110014",
    "110017",
    "110062",
    "110049",
    "110003",
    "110049",
    "110017",
    "110080",
    "110065",
    "110076",
    "110017",
    "110017",
    "110065",
    "110025",
    "110010",
    "110010",
    "110038",
    "110021",
    "110029",
    "110010",
    "110047",
    "110047",
    "110010",
    "110061",
    "110074",
    "110010",
    "110021",
    "110074",
    "110010",
    "110010",
    "110010",
    "110030",
    "110030",
    "110016",
    "110016",
    "110016",
    "110037",
    "110068",
    "110016",
    "110067",
    "110047",
    "110067",
    "110097",
    "110023",
    "110023",
    "110010",
    "110030",
    "110023",
    "110037",
    "110068",
    "110021",
    "110047",
    "110070",
    "110030",
    "110021",
    "110067",
    "110021",
    "110037",
    "110023",
    "110016",
    "110037",
    "110030",
    "110010",
    "110066",
    "110022",
    "110022",
    "110022",
    "110022",
    "110022",
    "110022",
    "110022",
    "110022",
    "110066",
    "110010",
    "110038",
    "110029",
    "110074",
    "110023",
    "110074",
    "110074",
    "110061",
    "110010",
    "110021",
    "110010",
    "110010",
    "110030",
    "110030",
    "110016",
    "110070",
    "110070",
    "110057",
    "110057",
    "110077",
    "110075",
    "110075",
    "110045",
    "110078",
    "110064",
    "110064",
    "110078",
    "110045",
    "110045",
    "110046",
    "110009",
    "110009",
    "110085",
    "110089",
    "110085",
    "110085",
    "110088",
    "110018",
    "110026",
    "110018",
    "110018",
    "110059",
    "110058",
    "110015",
    "110078",
    "110015",
    "110078",
    "110058",
    "110058",
    "110058",
    "110027",
    "110059",
    "110015",
    "110077",
    "110063",
    "110063",
    "110026",
    "110026",
    "110027",
    "110027",
    "110015",
    "110026",
    "110027",
    "110027",
    "110087",
    "110027",
    "110018",
    "110018",
    "110018",
    "110018",
    "122001",
    "122001",
    "122017",
    "122002",
    "122008",
    "122010",
    "122002",
    "122009",
    "122001",
    "122001",
    "122001",
    "122003",
    "122011",
    "122001",
    "122018",
    "122003",
    "122052",
    "122016",
    "122007",
    "122108",
    "122051",
    "122001",
    "122108",
    "122004",
    "122002",
    "122001",
    "122051",
    "122015",
    "122017",
    "122108",
    "122015",
    "122001",
    "122001",
    "122001",
    "560063",
    "560007",
    "560007",
    "560092",
    "560024",
    "560045",
    "560064",
    "560047",
    "560043",
    "560001",
    "560025",
    "560103",
    "560046",
    "560049",
    "560049",
    "560063",
    "560092",
    "560093",
    "560001",
    "560025",
    "560064",
    "560067",
    "560036",
    "560077",
    "560037",
    "560071",
    "560016",
    "560001",
    "560077",
    "560066",
    "560005",
    "560065",
    "560087",
    "560024",
    "560008",
    "560051",
    "560024",
    "560001",
    "560048",
    "560043",
    "560008",
    "560038",
    "560094",
    "560006",
    "560064",
    "560043",
    "560075",
    "560067",
    "560067",
    "560043",
    "560067",
    "560092",
    "560077",
    "560016",
    "560036",
    "560037",
    "560001",
    "560084",
    "560048",
    "560001",
    "560037",
    "560033",
    "560067",
    "560049",
    "560025",
    "560087",
    "560017",
    "560075",
    "560032",
    "560103",
    "560032",
    "560094",
    "560064",
    "560001",
    "560016",
    "560037",
    "560025",
    "560080",
    "560092",
    "560064",
    "560042",
    "560084",
    "560006",
    "560087",
    "560001",
    "560045",
    "560001",
    "560017",
    "560049",
    "560047",
    "560066",
    "560064",
    "560064",
    "560001",
    "560030",
    "560034",
    "560108",
    "560050",
    "560070",
    "560085",
    "560050",
    "560002",
    "560076",
    "560083",
    "560004",
    "560068",
    "560056",
    "560068",
    "560099",
    "560035",
    "560018",
    "560099",
    "560081",
    "560053",
    "560061",
    "560060",
    "560050",
    "560026",
    "560029",
    "560062",
    "560100",
    "560019",
    "560085",
    "560083",
    "560026",
    "560102",
    "560076",
    "560076",
    "560078",
    "560041",
    "560070",
    "560011",
    "560105",
    "560078",
    "560076",
    "560105",
    "560085",
    "560062",
    "560034",
    "560034",
    "560095",
    "560078",
    "560011",
    "560068",
    "560056",
    "560004",
    "560076",
    "560076",
    "560039",
    "560070",
    "560004",
    "560083",
    "560098",
    "560059",
    "560027",
    "560027",
    "560034",
    "560050",
    "560061",
    "560029",
    "560109",
    "560004",
    "560041",
    "560070",
    "560110",
    "560027",
    "560100",
    "560078",
    "560073",
    "560002",
    "560009",
    "560091",
    "560079",
    "560040",
    "560073",
    "560021",
    "560104",
    "560091",
    "560010",
    "560014",
    "560013",
    "560015",
    "560079",
    "560009",
    "560079",
    "560112",
    "560058",
    "560023",
    "560086",
    "560003",
    "560055",
    "560054",
    "560054",
    "560072",
    "560073",
    "560096",
    "560073",
    "560003",
    "560057",
    "560058",
    "560058",
    "560010",
    "560010",
    "560012",
    "560020",
    "560054",
    "560021",
    "560003",
    "560097",
    "560040",
    "560040",
    "560003",
    "560086",
    "560022",
    "560022",
    "201306",
"201309",
"201307",
"201307",
"201301",
"201301",
"203207",
"201304",
"201303",
"201305",
"201303",
"201301",
"201303",
"600018",
"600020",
"600082",
"600029",
"600040",
"600102",
"600101",
"600002",
"600106",
"600083",
"600023",
"600090",
"600108",
"600021",
"600113",
"600020",
"600018",
"600032",
"600001",
"600005",
"600031",
"600002",
"600112",
"600094",
"600106",
"600012",
"600032",
"600025",
"600003",
"600003",
"600008",
"600032",
"600018",
"600025",
"600118",
"600008",
"600084",
"600028",
"600009",
"600082",
"600014",
"600021",
"600086",
"600002",
"600001",
"600006",
"600032",
"600015",
"600104",
"600017",
"600038",
"600036",
"600020",
"600083",
"600014",
"600082",
"600078",
"600013",
"600020",
"600024",
"600010",
"600010",
"600024",
"600118",
"600021",
"600012",
"600085",
"600107",
"600092",
"600005",
"600033",
"600014",
"600034",
"600001",
"600002",
"600003",
"600005",
"600005",
"600033",
"600004",
"600001",
"600033",
"600079",
"600001",
"600004",
"600035",
"600107",
"600010",
"600034",
"600034",
"600034",
"600006",
"600030",
"600003",
"600005",
"600011",
"600012",
"600012",
"600011",
"600018",
"600014",
"600002",
"600012",
"600084",
"600028",
"600082",
"600022",
"600028",
"600024",
"600013",
"600003",
"600014",
"600004",
"600013",
"600118",
"600015",
"600015",
"600015",
"600093",
"600004",
"600011",
"600001",
"600006",
"600020",
"600030",
"600079",
"600092",
"600012",
"600018",
"600018",
"600006",
"600020",
"600017",
"600017",
"600017",
"600113",
"600005",
"600041",
"600041",
"600081",
"600081",
"600081",
"600014",
"600113",
"600026",
"600042",
"600012",
"600007",
"600092",
"600004",
"600039",
"600039",
"600021",
"600021",
"600033",
"600031",
"600056",
"600095",
"600116",
"600044",
"600047",
"600064",
"600075",
"600119",
"600097",
"600010"
  ];
  var ZipCodes2=[{
    "zipcode": "68130-1000",
    "city_name": "<NAME>",
    "charges":400,
  }
]

  return (
    <MenuContext.Provider
      value={{
        menu,
        cuisines,
        allMenus,
        cities,
        occasions,
        PreSelectMenuNinjaBox,
        ZipCodes
      }}
    >
      {children}
    </MenuContext.Provider>
  );
}

export function useAppMenu() {
  return useContext(MenuContext);
}
