// export const Testimonials_Data = [
//   {
//     name: "Hari om Gangwar",
//     place: "CEO",
//     image: "https://lh3.googleusercontent.com/a-/AFdZucreJwujTsy0QJ5wiZCv5yObPtQJMUCI59BkMufBXQ=w75-h75-p-rp-mo-br100",
//     content: "I had a snack box party for 90 kids with CaterNinja. It was delivered to me before time and the delivery person was friendly and helped me in keeping the boxes at my place. Kids loved the donuts, spring rolls and veg sliders a lot. Hassle free and best experience for me. Highly recommend to everyone looking for professional catering requirements. ",
//     product: 'NinjaLorem',
//   },
//   {
//     name: "Ananya Rai",
//     place: "CEO",
//     image: "https://lh3.googleusercontent.com/a-/AFdZucqzXpN_6LryRHbXQ54FDrwZTyGXIeCd_QNQ83L-Ivo=w75-h75-p-rp-mo-br100",
//     content: "I ordered ninja buffet service for the third time. This time food was best out of all 3 times. All my guests liked the food. There was no extra oil and masala. The food was like a home cooked meal. Dahi vadas we’re too good nice, soft and spongy. The service of servers was completely fuss free and excellent.",
//     product: 'NinjaLorem',
//   },
//   {
//     name: "Umesh Kadam",
//     place: "CEO",
//     image: "https://lh3.googleusercontent.com/a-/AFdZucrynkTzdd_nqZ6500Op9nBQvTQmPq59NC6pLkt-8w=w75-h75-p-rp-mo-ba3-br100",
//     content: "Hi Suma and team caterninja, I am pleased to share my positive feedback. Quality, Quantity and taste of all the food items were awesome. Packaging of all was top notch. Surely will be my first choice for any such event and also will share this with my friends.. ",
//     product: 'NinjaLorem',
//   },
//   {
//     name: "Rohit Saxena",
//     place: "CEO",
//     image: "https://lh3.googleusercontent.com/a-/AFdZucqNVAfasbNxclbPZ6ExhfWXqbfecUtDykjg86PV=w75-h75-p-rp-mo-br100",
//     content: "Good food and good packing. Very convenient and hassle free. I could plan other things better cause I didn't have to bother much about the food part. All guest liked the food.",
//     product: 'NinjaLorem',
//   },
//   ,
//   {
//     name: "Pragya Khetan",
//     place: "CEO",
//     image: "https://lh3.googleusercontent.com/a-/AFdZucpcsauSqUCykaPoJZh7NyLt55IUTqiBLB5RK_Yb5w=w75-h75-p-rp-mo-br100",
//     content: "Very good service, excellent food, customised food also available. The food was well packed and hassle free. No cutlery needed to be set.",
//     product: 'NinjaLorem',
//   },
//   ,
//   {
//     name: "Manish Waghodkar",
//     place: "CEO",
//     image: "https://lh3.googleusercontent.com/a-/AFdZucqDV72wops58jOj5tVqe2q7VTTPjvszWNLS9vrbng=w75-h75-p-rp-mo-br100",
//     content: "I had the best experience with any catering service in life with caterninja.We have a suprise birthday party of a friend that we have arranged with caterninja, all I can say is it was the best suprise we had because of them.The menus were colourful and the service guys were very helpful in serving the food. Overall I can say no words for the best service they provide, you have to try it on your own to be honest to experience the greatness they have to offer.",
//     product: 'NinjaLorem',
//   },
// ];
